=== danielzhang/GLS/trunk/modules/geocoding/src/main/resources/conf/classification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/classification" xmlns="http://www.example.org/classification"
	elementFormDefault="qualified">
	<!-- 该文档为分级评分规则表的XML Schema表: 节点名称统一大写英文单词，属性为小写英文单词 -->
	<xsd:element name="classification">
		<!-- 文档根节点为 CLASSIFICATION RULE -->

		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="score" maxOccurs="1" minOccurs="1">
				</xsd:element>
				<xsd:element name="engine" maxOccurs="unbounded"
					minOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<!-- 文档根节点为 根节点中包含不少于一个的子节点：LEVEL -->
							<!-- LEVEL的数量表述指定的分级数量 -->
							<xsd:element name="level" maxOccurs="unbounded"
								minOccurs="1">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="situation" minOccurs="1"
											maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<!-- LEVEL包含了一个或多个子节点LEVEL_ELEMENT -->
													<!-- LEVEL_ELEMENT表述在该级别下所包含的要素如“2”，“6”等 -->
													<xsd:element name="element" minOccurs="1"
														maxOccurs="unbounded">
														<xsd:complexType>
															<!-- LEVEL_ELEMENT包含1个必填属性 tag:为查询字段中包含要素的名称 如“2”，“6” -->
															<xsd:attribute name="tag" type="xsd:string"
																use="required"></xsd:attribute>
															<!-- description为描述性能容 -->
															<xsd:attribute name="description" type="xsd:string"></xsd:attribute>
														</xsd:complexType>
													</xsd:element>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
									<!-- 根节点包含两个必填属性 level 和 grade -->
									<!-- level 表述所处级别 -->
									<xsd:attribute name="index" type="xsd:integer" use="optional"
										></xsd:attribute>
									<!-- grade 表述该级别对应的分数 -->
									<!-- <xsd:attribute name="min_grade" type="xsd:integer" -->
									<!-- use="required"></xsd:attribute> -->
									<xsd:attribute name="grade" type="xsd:float" use="required"></xsd:attribute>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="name" type="xsd:string"></xsd:attribute>
						<xsd:attribute name="selector" type="xsd:string"></xsd:attribute>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== danielzhang/GLS/modules/geocoding/src/main/resources/conf/classification.xml
<?xml version="1.0" encoding="GB2312"?>
<!DOCTYPE classification >
<classification xmlns:tns="http://www.example.org/classification"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/classification classification.xsd">
	
	<score>10</score>
	<engine name="地址" selector="Address">
		<weight>
		    <level tag="4" value="1"/>
			<level tag="5" value="2" />
			<level tag="6" value="4" />
			<level tag="16" value="4"/>
			<level tag="8" value="7"/>
			<level tag="18" value="4"/>
			<level tag="9" value="5"/>
			<level tag="19" value="3"/>
			<level tag="10" value="5"/>
			<level tag="20" value="3"/>
		</weight>
		<level index="1">
			<situation>
				<element tag="10" description="大厦" />
				<element tag="20" description="大厦后缀" />
			</situation>
			<situation>
				<element tag="10" description="大厦" />
			</situation>
		</level>

		<level index="2">
			<situation>
				<element tag="9" description="小区/学校" />
				<element tag="19" description="小区/学校后缀" />
			</situation>
			<situation>
				<element tag="9" description="小区/学校" />
			</situation>
		</level>

		<level index="3">
			<situation>
				<element tag="8" description="道路" />
			</situation>
			<situation>
				<element tag="8" description="道路" />
				<element tag="18" description="道路后缀" />
			</situation>
		</level>
		<level index="4">
			<situation>
				<element tag="16" />
				<element tag="6"  />
			</situation>
			<situation>
				<element tag="6" />
			</situation>
		</level>
	</engine>


	<engine name="城市" selector="city">
		<level grade="10" index="1">
			<situation>
				<element tag="3"/>
			</situation>
		</level>
	</engine>

	<engine name="区县行政区划" selector="political">
		<level grade="30" index="1">
			<situation>
				<element tag="4" />
			</situation>
		</level>
	</engine>

	<engine name="镇行政区划" selector="political">
		<level grade="40">
			<situation>
				<element tag="5"/>
			</situation>
		</level>
	</engine>
	
	<engine name="村行政区划" selector="political">
		<level grade="50"  index="1">
			<situation>
				<element tag="6"/>
			</situation>
		</level>
	</engine>

	<engine name="路" selector="road">
		<level grade="80" >
			<situation>
				<element tag="18"/>
			</situation>
		</level>
	</engine>

	<engine name="交叉口" selector="intersection">
		<level grade="90" index="1">
			<situation>
				<element tag="7"  />
			</situation>
		</level>
	</engine>


</classification>
